### ISSUE TITLE
Mean phylogenetic distance?

### ISSUE THREAD

**Issue by joelnitta** [darunabas/phyloregion#1]
Thanks for the great package! The speed-ups are awesome. This is a feature request: have you considered adding a function for mean phylogenetic distance (like in picante)? That would be nice, since it could also be used for trait distances.

**Comment by KlausVigo** [comment]
Hi @joelnitta,
can you give a short example what you refer to exactly. There is a function `mean_dist` in `phyloregion`, but I am not sure if this is what you are looking for.
Regards, 
Klaus

**Comment by darunabas** [comment]
> Thanks for the great package! The speed-ups are awesome. This is a feature request: have you considered adding a function for mean phylogenetic distance (like in picante)? That would be nice, since it could also be used for trait distances.

Hi @joelnitta 
If I understand you correctly, did you mean mean phylogenetic distance i.e. mean pairwise distance similar to that implemented in picante (function mpd in picante)? Would you prefer a faster version of that?

**Comment by joelnitta** [comment]
@KlausVigo, I had a look at `mean_dist()`, but it doesn't seem to be what I have in mind.

@darunabas, yes that is what I meant: drop-in replacements for `picante::mpd()` and `picante::mntd()`. In a study comparing various community diversity metrics, these were shown to be distinct from Faith's PD ([Tucker et al 2017](https://onlinelibrary.wiley.com/doi/full/10.1111/brv.12252)).
