### ISSUE TITLE
Errors during converting polygon data to community matrix

### ISSUE THREAD

**Issue by duyuanbao** [darunabas/phyloregion#15]
Dear all,
I just expected to repeat the biogeographical analysis using the package of phyloregion.

Using the code provided by the authors and the reptile distribution data as the authors used in the MEE, the process did not work and an error occurred when I run the function 'polys2comm'. The code lines are as follow:

#install.packages("phyloregion")
library(phyloregion)
library(ape)
library(Matrix)
library(terra)
library(raster)
library(rgdal)
library(stringr)
setwd("D:/R-analysis/zoogeography")

##########using reptile data to test
my_spdf <- readOGR(dsn= paste0("D:/R-analysis/zoogeography/reptile") , layer="Gard_1_7_ranges", verbose=TRUE)
###### I also tried using the shapefile function in raster package#####
##my_spdf <- shapefile("D:/R-analysis/zoogeography/reptile/Gard_1_7_ranges.shp")

head(my_spdf)
comm<- polys2comm(my_spdf,res=2,species="binomial")
_Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘relate’ for signature ‘"SpatialPolygonsDataFrame", "SpatVector"’_

When I tried using the amphibian distribution data from IUCN to test it, I got another issues when I run 'polys2comm'. And the code lines are as follow:

my_spdf <- readOGR(dsn= paste0("D:/R-analysis/zoogeography/shapefiles") , layer="AMPHIBIANS", verbose=TRUE)
head(my_spdf)
comm<- polys2comm(my_spdf,res=2,species="sci_name")
_Error in names(x@data) <- value : 
  'names' attribute [1] must be the same length as the vector [0]_

Any advice to fix these errors will be appreciated!

**Comment by darunabas** [comment]
v <- vect("/Users/bdaru/Downloads/TETRAPODS/REPTILES/Gard_1_7_ranges.shp")
Dear @duyuanbao 

In our recent update of `phyloregion`, we have removed dependencies on retiring packages such as rgdal, sp, and even raster. The functions that depended on these packages now called on terra which is much efficient and faster for most biogeographical investogations. To this end, here's how I would revise your code: 
 ```R
# install.packages("phyloregion")
library(phyloregion)
library(terra)

# Set working directory
setwd("D:/R-analysis/zoogeography")

# Using reptile data to test
my_spdf <- vect("D:/R-analysis/zoogeography/reptile/Gard_1_7_ranges.shp")

# head(my_spdf)
#               binomial TaxonID  group    family       area
# 1 Ablepharus bivittatus  R06992 lizard Scincidae 1124272.16
# 2     Ablepharus budaki  R06993 lizard Scincidae  121183.37
# 3   Ablepharus chernovi  R06994 lizard Scincidae  296008.89
# 4    Ablepharus darvazi  R06995 lizard Scincidae   30666.05
# 5    Ablepharus deserti  R06996 lizard Scincidae  889038.26
# 6   Ablepharus grayanus  R06997 lizard Scincidae  230806.84

# Create a community matrix with resolution of 2 degrees based on EPSG:4326 map projection
z <- polys2comm(my_spdf, res = 2)

There will be two outputs, `comm_dat` (sparse community matrix) and `map` (vector of grid cells with the values per cell for mapping).

The same approach should hold for the amphibian data. 
I hope this helps.
