### ISSUE TITLE
All data and scripts necessary to repeat the analyses for the squamate reptiles were unavailable？

### ISSUE THREAD

**Issue by Otoliths** [darunabas/phyloregion#2]
Hi @darunabas 
All data and scripts necessary to repeat the analyses for the squamate reptiles described here have been made unavailable through the Dryad Digital Data Repository https://doi.org/10.5061/dryad.tdz08kpw6 (Daru et al. 2019).

**Comment by darunabas** [comment]
Hi @Otoliths 
Thanks for your note. Because the manuscript describing the phyloregion package is currently under review for journal publication, DRYAD automatically restricts access to the dataset until the paper is published. I am happy to share some scripts or data directly if necessary.

**Comment by Otoliths** [comment]
Hi @darunabas
Thanks a million! I'm looking forward to it.

**Comment by patarol** [comment]
@darunabas I believe we can close this thread, right?! (cc @KlausVigo )
